### PR TITLE
added barycentric correction method to EchelleSpectrum

### PR DESCRIPTION
**Pull request by tzdwi**

### CODE REVIEW

**Comment by bmorris3** [comment]
@tzdwi Tests are failing – did you move/remove the example WR spectrum file hosted on your webpage?

**Comment by tzdwi** [comment]
crap yes i totally did. what URL do the tests point to? I'll put it back there.

**Comment by tzdwi** [comment]
found it; i don't know how to rerun the checks but they should be fixed.

**Comment by bmorris3** [comment]
Just restarted the build 👍

**Comment by tzdwi** [comment]
[https://giphy.com/gifs/reaction-disney-the-emperors-new-groove-HCzHAqlF7iqre](url)

**Pull request merged**
